const fs=require('fs'),path=require('path'),ts=require('typescript'),assert=require('node:assert/strict');
const temp=fs.mkdtempSync('/tmp/bbf-check-');for(const f of ['config','persistence','audio','input','world'])fs.writeFileSync(path.join(temp,f+'.js'),ts.transpileModule(fs.readFileSync('src/game/'+f+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);
global.window={addEventListener(){},removeEventListener(){}};global.document={addEventListener(){},removeEventListener(){},hidden:false};global.HTMLInputElement=class{};const storage=new Map;global.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
const{World}=require(path.join(temp,'world.js')), {C}=require(path.join(temp,'config.js'));let count=0;
function test(name,fn){fn();console.log('PASS '+name);count++}
function fresh(){const w=new World(()=>{});w.audio.unlock=()=>{};w.audio.sound=()=>{};w.start(false);w.spawnTimer=999;return w}
function step(w,s){for(let i=0;i<s*120;i++)w.tick(1/120)}
test('jab anticipation, glove range, once per attack, recovery',()=>{const w=fresh();w.add('bruiser',740);w.input.set('a','jab',true);step(w,.045);assert.equal(w.enemies[0].hp,4);step(w,.045);assert.equal(w.enemies[0].hp,3);step(w,.1);assert.equal(w.enemies[0].hp,3);const v=fresh();v.add('bruiser',840);v.input.set('a','jab',true);step(v,.2);assert.equal(v.enemies[0].hp,4)});
test('full charge deals 3, hits multiple, interrupts bruiser',()=>{const w=fresh();w.add('bruiser',730);w.add('pinata',755);w.enemies[0].state='warn';w.enemies[0].timer=2;w.input.set('a','charge',true);step(w,.71);w.input.set('a','charge',false);step(w,.1);assert.equal(w.enemies.find(e=>e.kind==='bruiser').hp,1);assert.equal(w.enemies.find(e=>e.kind==='bruiser').state,'recover');assert.equal(w.kills,1)});
test('dodge direction, immunity, cooldown; damage immunity and loss',()=>{const w=fresh();w.input.set('a','left',true);w.input.set('b','dodge',true);step(w,.02);assert.equal(w.player.face,-1);assert.ok(w.player.dodge>0);w.hurt();assert.equal(w.player.hp,5);step(w,.3);w.hurt();assert.equal(w.player.hp,4);w.hurt();assert.equal(w.player.hp,4);w.input.clear();for(let i=0;i<4;i++){step(w,1.01);w.hurt()}assert.equal(w.mode,'over')});
test('no contact damage; warnings last at least 400ms',()=>{for(const kind of ['cupcake','bruiser','pinata','caster']){const w=fresh();w.add(kind,kind==='caster'?1000:650);w.enemies[0].timer=0;step(w,.4);assert.equal(w.player.hp,5);assert.equal(w.enemies[0].state,'warn')}});
test('special charges on 20 successful hits, radial damage, clears projectiles',()=>{const w=fresh();for(let i=0;i<20;i++){w.add('cupcake',700);const e=w.enemies.at(-1);w.hit(e,1,false);w.enemies=[]}assert.equal(w.special,20);w.add('bruiser',700);w.add('bruiser',1100);w.projectiles.push({x:500,y:520,vx:100,vy:0,life:5});w.specialAttack();assert.equal(w.special,0);assert.equal(w.player.hp,5);assert.equal(w.enemies[0].hp,-1);assert.equal(w.enemies[1].hp,4);assert.equal(w.projectiles.length,0)});
test('combo thresholds, expiry, damage reset and score',()=>{const w=fresh();for(let i=0;i<20;i++){w.add('bruiser',700);w.hit(w.enemies.at(-1),1,false);w.enemies=[];assert.equal(w.mult(),i>=19?4:i>=9?3:i>=4?2:1)}step(w,2.01);assert.equal(w.combo,0);w.combo=10;w.hurt();assert.equal(w.combo,0);assert.ok(w.score>0)});
test('candy proximity, eight-second expiry, pinata extra loot',()=>{const w=fresh();w.candies=[{x:640,life:8},{x:1200,life:8}];step(w,.02);assert.equal(w.score,75);assert.equal(w.candies.length,1);step(w,8.1);assert.equal(w.candies.length,0);w.add('pinata',700);w.hit(w.enemies[0],3,true);assert.equal(w.candies.length,5)});
test('boss rotates slam/spread/summon, cap; second phase faster',()=>{const w=fresh();w.add('boss',1000);const e=w.enemies[0];for(let i=0;i<3;i++){e.state='warn';e.timer=.01;w.tick(.02);e.state='recover';e.timer=2}assert.equal(e.action,3);assert.equal(w.projectiles.length,3);assert.equal(w.warning.length,2);e.hp=14;e.state='walk';e.timer=0;w.tick(.02);assert.equal(e.timer,.65);for(let i=0;i<20;i++)w.add('cupcake',50);assert.equal(w.enemies.filter(e=>e.kind!=='boss').length,8)});
test('pause freezes all timers; blur clears inputs; restart resets all state',()=>{const w=fresh();w.input.set('a','left',true);w.pause();const t=w.time;step(w,3);assert.equal(w.time,t);assert.equal(w.input.held.size,0);w.play();w.add('bruiser',400);w.projectiles=[{x:2,y:2,vx:1,vy:1,life:4}];w.score=500;w.wave=4;w.player.hp=1;w.special=20;w.start(false);assert.equal(w.enemies.length,0);assert.equal(w.projectiles.length,0);assert.equal(w.wave,1);assert.equal(w.player.hp,5);assert.equal(w.score,0);assert.equal(w.special,0);w.input.blur();assert.equal(w.mode,'paused');w.quit();assert.equal(w.mode,'title')});
test('best persists; unavailable storage is harmless',()=>{const w=fresh();w.score=1234;w.finish('over');assert.equal(new World(()=>{}).best,1234);global.localStorage={getItem(){throw Error()},setItem(){throw Error()}};const a=fresh();a.finish('over');assert.equal(a.best,0)});
test('simultaneous touch sources, charge release and focus loss',()=>{const w=fresh();const i=w.input;i.set('touch1','left',true);i.set('touch2','jab',true);assert.ok(i.held.has('left')&&i.held.has('jab'));i.set('touch3','jab',true);i.set('touch2','jab',false);assert.ok(i.held.has('jab'));i.set('touch3','jab',false);assert.ok(!i.held.has('jab'));i.set('touch4','charge',true);i.frame();i.set('touch4','charge',false);assert.ok(i.released.has('charge'));i.blur();assert.equal(i.held.size,0);assert.equal(w.mode,'paused')});
test('movement is consistent at 30, 60 and 120 FPS',()=>{for(const fps of [30,60,120]){const w=fresh();w.input.set('key','right',true);for(let i=0;i<fps;i++)w.tick(1/fps);assert.ok(Math.abs(w.player.x-960)<.001)}});
test('jab punches away a candle; projectile deals one damage',()=>{const w=fresh();w.projectiles=[{x:700,y:525,vx:-50,vy:0,life:5}];w.input.set('key','jab',true);step(w,.1);assert.equal(w.projectiles.length,0);assert.equal(w.player.hp,5);const v=fresh();v.projectiles=[{x:641,y:525,vx:-50,vy:0,life:5}];step(v,.1);assert.equal(v.player.hp,4)});
test('audio starts on interaction, independent volume, mute and pause',()=>{const{AudioBus}=require(path.join(temp,'audio.js'));const b=new AudioBus();assert.equal(b.ctx,undefined);let resumed=0;global.AudioContext=class{currentTime=0;destination={};resume(){resumed++;return Promise.resolve()}close(){return Promise.resolve()}createGain(){return{connect(){},gain:{value:0,setValueAtTime(n){this.value=n}}}}};b.unlock();assert.equal(resumed,1);b.setPaused(false);b.update({music:.5,effects:.8,mute:false,reduced:false,shake:true});assert.equal(b.music.gain.value,.09);assert.ok(Math.abs(b.fx.gain.value-.24)<.001);b.update({...b.prefs,mute:true});assert.equal(b.fx.gain.value,0);assert.equal(b.music.gain.value,0);b.update({...b.prefs,mute:false});b.setPaused(true);assert.equal(b.music.gain.value,0);b.destroy()});
// Full deterministic controller plays the actual simulation, without altering HP,
// enemies, progression, collision, combat cooldowns or spawn timing.
test('complete five-wave run with regular inputs and normal health',()=>{const w=fresh();w.spawnTimer=2;let lastWave=0,seen=new Set;let ticks=0;while(w.mode==='playing'&&w.time<600){const p=w.player;seen.add(w.wave);if(w.wave!==lastWave){console.log('  Enter wave '+w.wave+' at '+w.time.toFixed(1)+'s, hp '+p.hp);lastWave=w.wave}const living=w.enemies.filter(e=>e.hp>0);const e=living.sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];w.input.set('bot','jab',true);let dir=0,charge=false,dodge=false;if(e){const d=e.x-p.x,dist=Math.abs(d);dir=dist>85+ C.enemy[e.kind].r*.3?Math.sign(d):dist<35?-Math.sign(d):0;if(dir===0&&Math.sign(d)!==p.face)dir=Math.sign(d);const projectile=w.projectiles.find(b=>Math.abs(b.x-p.x)<100&&Math.sign(b.vx)===Math.sign(p.x-b.x));if(projectile)dodge=true;const danger=e.state==='warn'&&e.timer<.12&&dist<(e.kind==='boss'?220:140);if(danger){dodge=true;dir=-Math.sign(d)}if((e.kind==='bruiser'||e.kind==='pinata'||e.kind==='boss')&&dist<145&&!danger){charge=p.charge<.7;}if(p.charge>=.7)charge=false}w.input.set('l','left',dir<0);w.input.set('r','right',dir>0);w.input.set('c','charge',charge);if(dodge&&p.dodgeCd<=0)w.input.set('d','dodge',true);else w.input.set('d','dodge',false);if(w.special===20)w.input.set('s','special',true);else w.input.set('s','special',false);w.tick(1/120);ticks++}console.log('  Result '+JSON.stringify({mode:w.mode,seconds:w.time,score:w.score,hp:w.player.hp,kills:w.kills,waves:[...seen]}));assert.equal(w.mode,'victory');assert.equal(seen.size,5);assert.ok(w.kills>=47)});
console.log(count+' checks passed');fs.rmSync(temp,{recursive:true,force:true});
